require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

# TODO: Eventually this library should be better documented; sadly it is not yet
# NOTE: Good first contribution!
Style/Documentation:
  Enabled: false

# I prefer reduce/inject most of the time.
Style/EachWithObject:
  Enabled: false

# Sorry, community, but I don't think it's a good choice.
Style/GlobalStdStream:
  Enabled: false

# some rubocop versions report on this, but we don't want to change the code for this;
Style/ComparableClamp:
  Enabled: false
