# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{schulze-vote}
  s.version = '2.0.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Alessandro Rodi']
  s.date = %q{2015-12-10}
  s.description = %q{This gem is a Ruby implementation of the Schulze voting method (with help of the Floyd-Warshall algorithm), a type of the Condorcet voting methods.}
  s.email = %q{coorasse@gmail.com}
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.rspec',
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'examples/vote4.list',
    'examples/vote6.list',
    'lib/schulze-vote.rb',
    'lib/vote.rb',
    'lib/vote/condorcet.rb',
    'lib/vote/condorcet/schulze.rb',
    'lib/vote/condorcet/schulze/basic.rb',
    'lib/vote/condorcet/schulze/input.rb',
    'lib/vote/condorcet/schulze/win_and_lost.rb',
    'lib/vote/matrix.rb',
    'spec/spec_helper.rb',
    'spec/schulze_vote_spec.rb',
    'schulze-vote.gemspec'
  ]
  s.homepage = %q{http://github.com/coorasse/schulze-vote}
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Schulze method implementation in Ruby (Condorcet voting method)}

end

